// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type OptionsLegacyParser } from '@hey-api/client-fetch';
import type { HealthError, HealthResponse } from './types.gen';

export const client = createClient(createConfig());

export const health = <ThrowOnError extends boolean = false>(options?: OptionsLegacyParser<unknown, ThrowOnError>) => {
    return (options?.client ?? client).get<HealthResponse, HealthError, ThrowOnError>({
        ...options,
        url: '/health'
    });
};